function Jc1Symbols = Jc1Func(q1)
%JC1FUNC
%    JC1SYMBOLS = JC1FUNC(Q1)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Mar-2017 10:10:11

Jc1Symbols = reshape([sin(q1).*(-1.0./1.0e1),cos(q1).*(1.0./1.0e1),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,5]);
