function Jc5Symbols = Jc5Func(q1,q2,q3,q4,q5)
%JC5FUNC
%    JC5SYMBOLS = JC5FUNC(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 7.0.
%    02-Mar-2017 10:10:11

t2 = q1+q2+q3+q4+q5;
t3 = sin(t2);
t4 = q1+q2+q3;
t5 = sin(t4);
t6 = q1+q2+q3+q4;
t7 = sin(t6);
t8 = q1+q2;
t9 = sin(t8);
t10 = cos(t4);
t11 = t10.*(1.0./5.0);
t12 = cos(t6);
t13 = t12.*(1.0./5.0);
t14 = cos(t8);
t15 = t14.*(1.0./5.0);
t16 = cos(t2);
t17 = t16.*(1.0./1.0e1);
Jc5Symbols = reshape([t3.*(-1.0./1.0e1)-t5.*(1.0./5.0)-t7.*(1.0./5.0)-t9.*(1.0./5.0)-sin(q1).*(1.0./5.0),t11+t13+t15+t17+cos(q1).*(1.0./5.0),t3.*(-1.0./1.0e1)-t5.*(1.0./5.0)-t7.*(1.0./5.0)-t9.*(1.0./5.0),t11+t13+t15+t17,t3.*(-1.0./1.0e1)-t5.*(1.0./5.0)-t7.*(1.0./5.0),t11+t13+t17,t3.*(-1.0./1.0e1)-t7.*(1.0./5.0),t13+t17,t3.*(-1.0./1.0e1),t17],[2,5]);
